name: Code Style

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          make format
          git diff --exit-code
